### PR TITLE
Backporting: Missing Asset Fix

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
PR #6 was merged against `master`. In this PR we're just cherry-picking the fix, and resubmitting against `develop` instead.

cc @aerych @loremattei (Thank you both in advance!!)

### CODE REVIEW

**Comment by aerych** [comment]
Well spotted @jleandroperez  I missed that the target was `master`.

**Comment by jleandroperez** [comment]
Updated the base to `develop`... because... this one was also pointing to Master!!! thanks Eric!

**Comment by aerych** [comment]
This one has already been reviewed twice so maybe we can just :shipit:? :)

**Comment by jleandroperez** [comment]
Thank you Eric!!

**Comment by loremattei** [comment]
Thank you @aerych @jleandroperez! and sorry for missing the target in #6 :-(

**Comment by jleandroperez** [comment]
Thank *you*  Lorenzo!!!

**Pull request merged**
