### PR TITLE
Updated Google SignIn library to the major release 5

### LINKED ISSUE #236: Update the GoogleSignIn library when a version without UIWebView will be released
On Woo app, we continue to receive the message from Apple about the deprecated API usage for `UIWebView`.

It looks like `GoogleSignIn` does use UIWebView in their binaries:
```
-> % strings /Users/aaron/src/woocommerce-ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn  | grep -i uiwebview
l_OBJC_LABEL_PROTOCOL_$_UIWebViewDelegate
l_OBJC_PROTOCOL_$_UIWebViewDelegate
l_OBJC_LABEL_PROTOCOL_$_UIWebViewDelegate
l_OBJC_PROTOCOL_$_UIWebViewDelegate
UIWebViewDelegate
B40@0:8@"UIWebView"16@"NSURLRequest"24q32
v24@0:8@"UIWebView"16
v32@0:8@"UIWebView"16@"NSError"24
@"UIWebView"
T@"UIWebView",W,N,V_webView
... 
```

In their [changelog](https://developers.google.com/identity/sign-in/ios/release) I don’t see any reference to `UIWebView`, so I believe that even updating to the latest version available (5.0.2), we will continue to see the warning. 
**The library will need to be updated when a version that does not use `UIWebView` will be available.**

### PR DESCRIPTION
**Pull request by pmusolino**
Fixes #236 

## Description
Both on WordPress and on WooCommerce we continue to receive a warning from Apple about the deprecated API usage for `UIWebView`. It turns out that the problem lies in the old version of Google SignIn (v.4) which still uses the `UIWebView`.
In this PR I updated the Google SignIn library to the major version `5.0.2`.
Maybe I can release a new 1.18.0 release before the PR will be merged ([1.17.0](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/279) will be released soon), instead of using the beta nomenclature. What do you think about it?

## Changes
- Remove any declarations of conformance to the `GIDSignInUIDelegate` protocol
- Instead of setting the GIDSignIn object's `uiDelegate` property to an object that conforms to the GIDSignInUIDelegate protocol, I set its `presentingViewController` property to the view controller that contains the Google Sign-in button.
- Now we don't need anymore to pass `sourceApplication` and `annotation` to `handleURL:`. 

## Testing
- For [WooCommerce](https://github.com/woocommerce/woocommerce-ios/pull/2319) just check the opened PR.
- For WordPress: in progress. I wasn't able at the moment to open the PR for WordPress because I encounter this error `Specs satisfying the `WordPressUI (~> 1.7.0), WordPressUI (= 1.7.0, ~> 1.7.0), WordPressUI (~> 1.6.0)` dependency were found, but they required a higher minimum deployment target.`. We need that this [PR](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/279) will be merged to master, and I will align my PR to master.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @pmusolino .

Thanks for doing this! 

> Maybe I can release a new 1.18.0 release before the PR will be merged (1.17.0 will be released soon), instead of using the beta nomenclature. What do you think about it?

I'm not sure that's necessary. I know we get warnings from Apple, but is one more release going to hurt anything?

Maybe @loremattei would be a better person to ask, what his preference is.

**Comment by pmusolino** [comment]
> I'm not sure that's necessary. I know we get warnings from Apple, but is one more release going to hurt anything?

@ScoutHarris absolutely no. 👍  The App Store will no longer accept new apps using `UIWebView` as of April 2020 and app updates using `UIWebView` as of December 2020.

**Comment by ScoutHarris** [comment]
Hey @pmusolino .

Coincidentally, I just started refactoring Google login, and decided to branch off of this to avoid future conflicts. As such, I went ahead and resolved the conflicts on this PR, which included updating WordPressUI 1.7.0. I hope that's ok, but now you can create a WPiOS PR. 😄

**Comment by pmusolino** [comment]
Thank you so much both @ScoutHarris @mindgraffiti! I bumped the podspec to 1.17.0-beta.3, in that way I can publish a pre-release 👍

**Comment by pmusolino** [comment]
I will open a PR on WPiOS which points directly to 1.17.0-beta.3

**Pull request merged**
