### PR TITLE
Updates to WordPressKit with Alamofire 5

### PR DESCRIPTION
**Pull request by Gio2018**
This PR updates WordPressKit to the version that was upgraded to Alamofire 5

**Note: do not merge before updating the Podfile with the correct version on WordPressKit. Now it's pointing directly to a branch**

### CODE REVIEW

**Comment by yaelirub** [comment]
👋  @Gio2018, can we close this PR?

**Comment by Gio2018** [comment]
> 👋 @Gio2018, can we close this PR?

Done!

**Comment by jaclync** [comment]
Hey @Gio2018! Any reasons this PR was not merged? I was hoping to use the Combine feature in [Alamofire 5.2.0](https://github.com/Alamofire/Alamofire/releases/tag/5.2.0), but realized that the authenticator/WordPressKit isn't ready.

**Comment by Gio2018** [comment]
> Hey @Gio2018! Any reasons this PR was not merged? I was hoping to use the Combine feature in [Alamofire 5.2.0](https://github.com/Alamofire/Alamofire/releases/tag/5.2.0), but realized that the authenticator/WordPressKit isn't ready.

Hey @jaclync , at the time we decided that it would be better to migrate away from Alamofire, as there were additional issues on WPiOS. I'll share some more details on slack with you.

**Pull request closed without merging**
