### PR TITLE
Passkeys: Don't show error if users cancels Passkey authentication

### PR DESCRIPTION
**Pull request by momo-ozawa**
## Description

Fixes an issue where an error was displayed when you exit out of Passkey authentication

### Before

https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/assets/6711616/c76c9fd1-311e-4d53-bee4-7c1eb71b0e75

### After

https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/assets/6711616/951a4b74-04a7-4163-8405-5ec95c508998

## How to test
Test via https://github.com/wordpress-mobile/WordPress-iOS/pull/22001

---

- [ ] I have considered if this change warrants release notes and have added them to the appropriate section in the `CHANGELOG.md` if necessary.

### CODE REVIEW

**Comment by momo-ozawa** [comment]
Hey @Ecarrion 👋 
I don't think we should show an error when canceling the Passkey authentication flow. Wdyt?

**Review by guarani — APPROVED** [review]
After canceling, if I try the passkey option again it fails with the message "Your session has expired, please go back to the login screen.". Is this expected? It's not a great user experience but the message is helpful & actionable, so I don't think it's a blocker.

**Comment by guarani** [comment]
I updated WordPressKit to point to the next major version since this library and WPiOS both depend on it. I hope that's ok 🙇

**Comment by Ecarrion** [comment]
Hi @momo-ozawa @frosty,

I initially decided to present the error flow when canceling for simplicity, because we can't cancel the flow and start again the passkeys process without regenerating the server nonces.

The "ideal" solution would be to have some state on the client side to track if the error was due to a cancelation to not start the passkeys flow from scratch but only from the signature. But at the time I didn't make that a priority 😅 

What do you think about changing the error message(but we still reset the flow/stack upon tapping "ok") to explain a little bit better what is happening. This would prevent the user to end up on a faulty state and having to tap on CTAs twice to still end up with error screens.

**Comment by momo-ozawa** [comment]
> I initially decided to present the error flow when canceling for simplicity, because we can't cancel the flow and start again the passkeys process without regenerating the server nonces.

@Ecarrion Ah I see! So showing an error when you cancel is expected at this point in time.

> What do you think about changing the error message(but we still reset the flow/stack upon tapping "ok") to explain a little bit better what is happening. This would prevent the user to end up on a faulty state and having to tap on CTAs twice to still end up with error screens.

Given that the current flow is intentional, and our priority is to merge https://github.com/wordpress-mobile/WordPress-iOS/pull/22001 and https://github.com/wordpress-mobile/WordPressKit-iOS/pull/646 into WPiOS 23.6, I think we can leave out this change for now and address it in a future release. Wdyt, @guarani? 

We can change the copy as Ernesto suggested, or consider a more robust solution that restarts the passkeys flow from the signature.

**Comment by momo-ozawa** [comment]
I'm closing this for now - we can revisit this in a different PR

**Pull request closed without merging**
