### PR TITLE
UL&S: Re-establishes "signed in" tracking.

### PR DESCRIPTION
**Pull request by diegoreymendez**
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14869

In WPiOS 15.6 we removed tracking of `signed_in` in some scenarios.  This PR re-establishes tracking `signed_in`.

For testing instructions please refer to the WPiOS PR.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @diegoreymendez . I don't see the podspec version has changed in `release/1.24.2`, so it should be done here, right?

**Review by mindgraffiti — CHANGES_REQUESTED** [review]
Hey Diego 👋 

I tested SIWA + password challenge + magic link login and I'm not getting the Track event to report. Full Tracks:

 🔵 Tracked: unified_login_step <flow: siwa_login, source: default, step: start>
🔵 Tracked: unified_login_step <flow: siwa_login, source: default, step: password_challenge>
🔵 Tracked: application_closed <last_visible_screen: Login View, time_in_app: 313, time_in_main_reader: 0, time_in_reader_filtered_list: 0, time_in_reader_post: 0>
🔵 Tracked: application_opened <>
🔵 Tracked: application_closed <last_visible_screen: Login View, time_in_app: 10, time_in_main_reader: 0, time_in_reader_filtered_list: 0, time_in_reader_post: 0>
🔵 Tracked: application_opened <>
🔵 Tracked: application_closed <last_visible_screen: Login View, time_in_app: 2, time_in_main_reader: 0, time_in_reader_filtered_list: 0, time_in_reader_post: 0>
🔵 Tracked: application_opened <>
🔵 Tracked: unified_login_interaction <click: dismiss, flow: siwa_login, source: default, step: password_challenge>
🔵 Tracked: application_closed <last_visible_screen: Login View, time_in_app: 17, time_in_main_reader: 0, time_in_reader_filtered_list: 0, time_in_reader_post: 0>
🔵 Tracked: login_magic_link_opened <>
🔵 Tracked: login_magic_link_succeeded <>
🔵 Tracked: application_opened <>
🔵 Tracked: welcome_no_sites_interstitial_shown <>
🔵 Tracked: unified_login_interaction <click: continue, flow: siwa_login, source: default, step: password_challenge>
🔵 Tracked: reader_following_shown <list: Followed Sites>
🔵 Tracked: select_interests_shown <>

**Comment by diegoreymendez** [comment]
@mindgraffiti - I found the issue at last.  I had added a guard in a spot that was causing issues.  Now that the guard is removed, tracking of `signed_in` for magic links is working again.

**Review by mindgraffiti — APPROVED** [review]
:shipit: 

🔵 Tracked: signed_in <dotcom_user: true, multifactor: false>

**Pull request merged**
