### PR TITLE
Update pod version to 1.34.0-beta.3 per CR feedback.

### PR DESCRIPTION
**Pull request by allendav**
To pick up https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/561

### CODE REVIEW

**Review by ctarda — APPROVED** [review]
:shipit:

**Comment by jaclync** [comment]
Oh no, I forgot to check the latest `develop` and my PR https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/564 also didn't get to bump the pod version again (from beta 2 to 3) 🤦🏻‍♀️. How about we merge this `1.34.0-beta.3` altogether for the latest `develop` @allendav, then we can ship another beta release?

**Comment by jaclync** [comment]
Hi @allendav! I merged the PR of the same change https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/566 so you probably don't need this anymore 🙂

**Comment by allendav** [comment]
Closing without merge as https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/commit/fc854d51c3600f13e91d859440923ec227cd493c covers this.

**Pull request closed without merging**
