### PR TITLE
Duplicate the login and signup flows

### LINKED ISSUE #187: Spike: Duplicate Login, Signin, and NUX folders
Duplicate the storyboards and classes. Reconnect the IBOutlets, IBActions, and content views to their duplicated classes.

Screen Shot 2020-02-24 at 3 49 20 PM

### Duplication Strategy:

- [x] Add a folder, `Unified Login & Signup`
- [x] Duplicate the classes and storyboards found in the `Signin`, `Signup`, and `NUX` folders 
- [x] Prefix all class names with `Auth`
- [x] Reconnect IBOutlets, IBActions, content views, and class names in the duplicated storyboards
- [ ] <s>Rename `NUX` classes to ... (TBD)</s>

### PR DESCRIPTION
**Pull request by mindgraffiti**
Closes #187 

This PR duplicates the classes found in the Login, Signup, and NUX folders. The old classes in those folders have been moved to a Legacy folder. All duplicated classes have the `Auth` prefix. 

### To test
1. In order to test the flow, download and apply [this patch](https://gist.github.com/mindgraffiti/c71a83f4d5662d48ee34afd110faa98a), using `git apply <path-to-patch>`. This will connect the duplicated flow to the Authenticator.
2. In WCiOS or WPiOS, change the podfile to use a local pod. The authenticator line will look similar to this: `pod 'WordPressAuthenticator', :path => '/Users/thuycopeland/WordPressAuthenticator-iOS/'`
3. Smoke-test flows and try to break it!

This PR does not change any class names (other than adding the prefix). It was easier to re-link classes using their existing names. Renaming will happen in the future.

Each ViewController in the duplicated flows should have a different colored background - seafoam green, pink, etc.

### CODE REVIEW

**Comment by jleandroperez** [comment]
@mindgraffiti Question for you Thuy!! What would be the purpose of duplicating all the things? Since this is effectively a fork (so to speak), wouldn't it be maybe easier to just start a new repository?

**Comment by mindgraffiti** [comment]
Good question @jleandroperez! It was a best guess. Here are the things the UL&S project need:

1. The ability to stay up-to-date with the `develop` branch
2. The ability to fall back to the old flows
3. The ability to iteratively release the code behind the scenes (controlled by feature flags or bools)

If it's better that I fork the project, I think can do that (not certain if I have permissions).

**Comment by jleandroperez** [comment]
@mindgraffiti It's completely and definitely up to you Thuy, has to be the approach that makes you feel comfortable the most.

(1) You'd also need to map changes made to legacy files, over to the new ones
(2) Is probably gonna be very tricky (since each class might be used in more than one flow)
(3) This is a very valid point

Another alternative is to tag master as the `latest stable release`, take note of the number of the release, and begin making small (and testable) changes.

But again, definitely up to you. I'll do my best to take a peek at this one tomorrow (afk-ish today, sick-ish =( )

**Comment by mindgraffiti** [comment]
@jleandroperez 

> Another alternative is to tag master as the latest stable release, take note of the number of the release, and begin making small (and testable) changes.

I'd be happy to do that but I'm not sure how---Authenticator is heavily coupled. Instead of reviewing this one, how about I chat with you and Stephenie about it during the meetup?

**Pull request closed without merging**
