### PR TITLE
Remove 1password framework usage.

### LINKED ISSUE #17516: Remove 1Password Framework from WPiOS
Ref: pOhUr-4dm-p2

Remove the 1Password Framework from [WP Authenticator](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS) and implement OS-supported password autofilling in [WPiOS](https://github.com/wordpress-mobile/WordPress-iOS).

### PR DESCRIPTION
**Pull request by diegoreymendez**
Closes https://github.com/wordpress-mobile/WordPress-iOS/issues/17516

This PR completely removes the 1Password dependency from the authenticator and cleans up our code around it.  I'm posting this PR but the work was done by @hassaansaleh.

This is a feature branch combining the work of these PRs: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/623, https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/625 and https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/626.

The changes were done transparently for the App so there are no required changes in WPiOS (or WCiOS).

## Testing:

1. Just build and make sure all is good.
2. Launch the App and login using 1Password.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Fyi, @hassaansaleh

**Review by frosty — APPROVED** [review]
Code changes look good, and I tested using this branch in WordPress-iOS and everything worked as expected. :shipit:

**Comment by mokagio** [comment]
I tested this as part of `19.0.0.0` with my credentials stored in 1Password, including the MFA token that gets copied to the clipboard.

My attempt was successful and I didn't notice any difference in the flow 👍 

~~cc @startuptester not sure if you're running WordPress iOS still, but even if that's not the case you'll know who to forward this to. Thanks!~~ I saw @tiagomar's [CfT post](https://make.wordpress.org/mobile/2022/01/10/call-for-testing-wordpress-for-ios-19-0/) 👌

**Comment by startuptester** [comment]
thanks @mokagio! It's not official yet, but the switch is in progress. Thanks tagging both of us!

**Pull request merged**
